production:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr/default'
    log_level: WARNING
    solr_home: solr
    # pid_dir: '/var/run'

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development
    solr_home: solr

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
