production:
  solr:
    hostname: localhost
    port: 8080
    path: '/solr'
    log_level: WARNING
    # pid_dir: '/var/run'

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
